name: Deploy to Fly.io

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: fly-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install flyctl (official way)
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        # Optional: pin the CLI version to avoid surprises:
        # with:
        #   version: 0.0.462

      # Ensure your app secret exists (safe to re-run). Remove if you manage secrets separately.
      - name: Set DISCORD_TOKEN secret on Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl secrets set DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}" --app siege-tracker-bot --stage

      # Deploy your app using the Dockerfile + fly.toml in the repo
      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --remote-only --app siege-tracker-bot
